### ISSUE TITLE
OS X Sierra fix.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [tolysz/ghcjs-stack#5]
The ghc distributed by homebrew does not work with ghcjs as of now.  The following addition to the `stack.yaml` file fixes it for me by using the older ghc-8.0.1 distributed by stack.

```
...
system-ghc: false
packages:
- location: .
- location:
    git:    https://github.com/haskell/haddock.git
    commit: 240bc38b94ed2d0af27333b23392d03eeb615e82
  subdirs:
  - haddock-api

extra-deps:
- haddock-api-2.17.3
```
